# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07926881aa9d742dd7bbc39abbf0ef405ed7bfd188ddb140e692f985d71f217ff331ed5f2696594a71b2af39a83602238629aa490dc70fa52424c062f3223b15

test:
  secret_key_base: d3b0211df2d914a0f5bcaf01120676e4e2877672470cd3d800a46e01b41833d8ea5ee4d699210e22b065aa4b20497ae55c86c4291c50f2c50fa6b938b582b5d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
